### PR TITLE
Updated base script to PSADT 3.6.9

### PR DESCRIPTION
**Pull request by bpenglase**

### CODE REVIEW

**Comment by bpenglase** [comment]
Forgot to comment out the Welcome message, that requires IE to be closed. I think that can be fixed before accepted.

**Comment by crossan007** [comment]
@bpenglase  What's SNAP?

**Comment by bpenglase** [comment]
SNAP Health Center, from ProMed/Professional Software for Nurses: http://www.promedsoftware.com/
Basically it's software for the school nurses to track students. Medications, schedules, vaccines, visits, etc. Not sure how many use it, and I know we're trying to get them over to eSchool for that functionality, since it would have more up to date contacts for parents and other such info. But for now, it's what they are using, so we have to support it.

The script also specifies the default server, so on first launch, it just connects instead of prompting them for a SQL Server to connect to.

**Comment by bpenglase** [comment]
Updating incoming... forgot to setup the uninstall section. Oops.
Was actually just the update I forgot.

**Comment by bpenglase** [comment]
Old Version at this point. Closing. Will update with new one.

**Pull request closed without merging**
